plugins:
  awesomeness_enabled:
    default: true
    client: true
  awesomeness_max_volume:
    default: 10
    client: true
  Themes_enabled:
    default: true
    client: true
required:
  logo:
    default: "/plugins/discourse-theme-sample/images/discourse.png"
    client: true
    type: upload
  logo_url:
    hidden: true
    default: "/plugins/discourse-theme-sample/images/discourse.png"
